# Generated by Django 3.2 on 2024-03-15 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenuser',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 11, 43, 56, 875622)),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
