# Generated by Django 3.2 on 2024-03-14 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokenuser',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 4, 58, 5, 868409)),
        ),
    ]
