# Generated by Django 3.2 on 2024-01-14 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tokenuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tokenuser',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 6, 14, 8, 142084)),
        ),
    ]
