# Generated by Django 3.2 on 2024-03-20 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240319_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokenuser',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 2, 27, 17, 234480)),
        ),
    ]
